# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5362c36af516c55c5b6fe999dbf1be51d70579dac5e1df0df8679426c0d163342c065eff1c529f69c5d2172d82f5745b8e14492e10cc8dac57a7b73b7e6aaa68

test:
  secret_key_base: 7a38d02e8e0c92c577a4252bc4fe462faa566e163d17e4f6f7ce3921cf09dc17e711cf828b7936ac399a3a8106bd7cb1a98f401aff097e49d3644df126fc5838

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
